heat_template_version: 2015-04-30

description: Template for using heat to create an instance

resources:

  y-network:
    type: OS::Neutron::Net
    
  y-router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: public-net }
    
  y-subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: "10.0.0.7/24"
      network: { get_resource: y-network }
   
  y-interface:  #attach router to subnet
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: y-router }
      subnet: { get_resource: y-subnet }
    
  y-security-group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules: [{"direction": "ingress",
      "port_range_min": 1,
      "port_range_max": 65535,
      "protocol": "tcp"}, 
      {"direction": "ingress",
      "port_range_min": 1,
      "port_range_max": 65535,
      "protocol": "udp"}] 
      
  y-port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: y-network }
      security_groups: [{get_resource: y-security-group}]
      
  y-floating-ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "public-net"
      
  associate-floating-ip:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: [y-interface]
    properties:
      floatingip_id: { get_resource: y-floating-ip }
      port_id: { get_resource: y-port }

  y-server:
    type: OS::Nova::Server
    depends_on: [y-interface, associate-floating-ip, y-floating-ip, 
    y-port, y-security-group, y-network, y-router, y-subnet]
    properties:
      key_name: mykey
      image: d8648a86-dc5d-45cb-8339-d4537dce4078 #ubuntu-20.04-x86_64
      flavor: 0ba691d3-3ff5-4403-843a-c7f8ff61ae4f #c1.c4r4
      networks: 
        - port: { get_resource: y-port } #Note nodejs dependent on curl
      user_data: |
        #!/bin/bash
        apt-get update
        apt-get install -y curl git
        curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
        apt-get install -y nodejs
        mkdir /etherpad
        cd /etherpad
        git clone --branch master https://github.com/ether/etherpad-lite.git
        cd ~
        cd /etc/systemd/system
        curl -fsSL https://raw.githubusercontent.com/yvonnewat/Heat/main/Systemd/run-etherpad.service
        systemctl daemon-reload
        systemctl enable run-etherpad.service
        systemctl start --no-block run-etherpad.service
        touch /deploy-complete
        
outputs:

  public_ip_address:
    description: Public IP address
    value: { get_attr: [ y-floating-ip, floating_ip_address ] }
